spring.application.name=integrador-api
spring.datasource.url=jdbc:mysql://localhost:3306/db_integrador?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dadosmain
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
